config/routes.rb
Rails.application.routes.draw do
  resources :game_words, defaults: {format: :json}
  resources :games, defaults: {format: :json}
  resources :users, except: [:new, :edit], defaults: {format: :json}
  resources :words, defaults: {format: :json}
  resources :songs, defaults: {format: :json}
  resources :sessions
  
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  post 'login' => 'users#get_token', as: :login
  post :token, controller: 'application'

  get 'wordsforsong' => 'words#for_song', as: :wordsforsong
  get 'gamewordsforgame' => 'game_words#for_game', as: :gamewordsforgame

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :song
  validates_presence_of :song_id, :description
  
  scope :for_song,   ->(song_id) { where(song_id: song_id) }
  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  def for_song
    @words = Word.all.for_song(word_params[:song_id])
    render json: @words
  end
  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)
    if @word.save
      render json: @word, status: :created, location: @word
    else
      render json: @word.errors, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    if @word.update(word_params)
      format.json { render :show, status: :ok, location: @word }
    else
      format.json { render json: @word.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    format.json { head :no_content }
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:description, :index, :text, :song_id)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>
      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.text_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Words</h1>

<table>
  <thead>
    <tr>
      <th>description</th>
      <th>Index</th>
      <th>Text</th>
      <th>Song ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.description %></td>
        <td><%= word.index %></td>
        <td><%= word.text %></td>
        <td><%= word.song_id %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @word.description %>
</p>

<p>
  <strong>Index:</strong>
  <%= @word.index %>
</p>

<p>
  <strong>Text:</strong>
  <%= @word.text %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>