config/routes.rb
Rails.application.routes.draw do
  resources :game_words, defaults: {format: :json}
  resources :games, defaults: {format: :json}
  resources :users, except: [:new, :edit], defaults: {format: :json}
  resources :words, defaults: {format: :json}
  resources :songs, defaults: {format: :json}
  resources :sessions
  
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  post 'login' => 'users#get_token', as: :login
  post :token, controller: 'application'

  get 'wordsforsong' => 'words#for_song', as: :wordsforsong
  get 'gamewordsforgame' => 'game_words#for_game', as: :gamewordsforgame

end

app/models/game_word.rb
class GameWord < ActiveRecord::Base
  belongs_to :game
  validates_presence_of :game_id, :word_id
  
  scope :for_game,   ->(game_id) { where(game_id: game_id) }
end

app/controllers/game_words_controller.rb
class GameWordsController < ApplicationController
  before_action :set_game_word, only: [:show, :edit, :update, :destroy]

  # GET /game_words
  # GET /game_words.json
  def index
    @game_words = GameWord.all
  end

  # GET /game_words/1
  # GET /game_words/1.json
  def show
  end

  # GET /game_words/new
  def new
    @game_word = GameWord.new
  end

  # GET /game_words/1/edit
  def edit
  end

  def for_game
    @game_words = GameWord.all.for_game(game_word_params[:game_id])
  #  render json: @game_words
    
  end
  
  # POST /game_words
  # POST /game_words.json
  def create
    @game_word = GameWord.new(game_word_params)
    if @game_word.save
      format.json { render :show, status: :created, location: @game_word }
    else
      format.json { render json: @game_word.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /game_words/1
  # PATCH/PUT /game_words/1.json
  def update
      if @game_word.update(game_word_params)
        format.json { render :show, status: :ok, location: @game_word }
      else
        format.json { render json: @game_word.errors, status: :unprocessable_entity }
      end
  end

  # DELETE /game_words/1
  # DELETE /game_words/1.json
  def destroy
    @game_word.destroy
    format.json { head :no_content }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_word
      @game_word = GameWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_word_params
      params.require(:game_word).permit(:game_id, :word_id, :text)
    end
end

app/helpers/game_words_helper.rb
module GameWordsHelper
end

app/views/game_words/_form.html.erb
<%= form_for(@game_word) do |f| %>
  <% if @game_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_word.errors.count, "error") %> prohibited this game_word from being saved:</h2>

      <ul>
      <% @game_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :word_id %><br>
    <%= f.number_field :word_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_words/edit.html.erb
<h1>Editing Game Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_word %> |
<%= link_to 'Back', game_words_path %>

app/views/game_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Words</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Word</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_words.each do |game_word| %>
      <tr>
        <td><%= game_word.game_id %></td>
        <td><%= game_word.word_id %></td>
        <td><%= game_word.text %></td>
        <td><%= link_to 'Show', game_word %></td>
        <td><%= link_to 'Edit', edit_game_word_path(game_word) %></td>
        <td><%= link_to 'Destroy', game_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game word', new_game_word_path %>

app/views/game_words/new.html.erb
<h1>New Game Word</h1>

<%= render 'form' %>

<%= link_to 'Back', game_words_path %>

app/views/game_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_word.game_id %>
</p>

<p>
  <strong>Word:</strong>
  <%= @game_word.word_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @game_word.text %>
</p>

<%= link_to 'Edit', edit_game_word_path(@game_word) %> |
<%= link_to 'Back', game_words_path %>